import { Component, signal } from '@angular/core';
import { DatePipe, NgClass, NgFor, NgIf } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';
import {
  BiomarkerHistoryItem,
  DocumentHistoryItem,
  InsightRecommendation,
  InsightHistoryItem,
  InsightSnapshotResponse,
  JobHistoryItem,
} from '../../core/models/api.models';

@Component({
  selector: 'app-history',
  standalone: true,
  imports: [NgFor, NgIf, NgClass, DatePipe, MatCardModule, MatButtonModule],
  template: `
    <mat-card>
      <h2>My Uploaded Documents</h2>
      <p>Server-driven history of your uploads and biomarker records.</p>
      <button mat-button (click)="reload()">Refresh</button>
    </mat-card>

    <mat-card *ngFor="let doc of documents()" class="history-item">
      <h3>{{ doc.fileName || 'Unnamed file' }}</h3>
      <p>Document ID: {{ doc.documentId }}</p>
      <p>Uploaded at: {{ doc.createdAtUtc | date:'medium' }}</p>
      <p>Doc status: {{ documentStatusLabel(doc.documentStatus) }}, Job status: {{ doc.latestJobStatus ? jobStatusLabel(doc.latestJobStatus) : '-' }}</p>
      <p>Biomarkers: {{ doc.biomarkerCount }} (manual: {{ doc.manualBiomarkerCount }})</p>
      <p *ngIf="doc.missingMandatoryBiomarkers?.length">Missing mandatory: {{ doc.missingMandatoryBiomarkers?.join(', ') }}</p>
      <div class="doc-actions">
        <button mat-stroked-button
          [color]="selectedDocId() === doc.documentId && activePanel() === 'insights' ? 'primary' : ''"
          (click)="loadDocumentInsights(doc.documentId)">Load Doc Insights</button>
        <button mat-stroked-button
          [color]="selectedDocId() === doc.documentId && activePanel() === 'insights' ? 'primary' : ''"
          [disabled]="generatingInsightsDocId() === doc.documentId"
          (click)="generateDocumentInsights(doc.documentId)">
          <span *ngIf="generatingInsightsDocId() !== doc.documentId">Generate Doc Insights</span>
          <span *ngIf="generatingInsightsDocId() === doc.documentId" class="btn-spinner-wrap">
            <span class="btn-spinner"></span> Generating...
          </span>
        </button>
        <button mat-stroked-button
          [color]="selectedDocId() === doc.documentId && activePanel() === 'biomarkers' ? 'primary' : ''"
          (click)="loadDocBiomarkers(doc.documentId)">Show Biomarkers</button>
        <button mat-stroked-button
          [color]="selectedDocId() === doc.documentId && activePanel() === 'jobs' ? 'primary' : ''"
          (click)="loadDocJobs(doc.documentId)">Show Jobs</button>
      </div>

      <div *ngIf="selectedDocId() === doc.documentId && activePanel() === 'insights'" class="insight-block">
        <div *ngIf="generatingInsightsDocId() === doc.documentId" class="generating-overlay">
          <span class="lg-spinner"></span>
          <p class="generating-text">Generating AI insights... this may take a moment.</p>
        </div>
        <ng-container *ngIf="selectedInsights() as insights">
          <p><strong>Note:</strong> Recommendations are generated by AI and should be clinically validated. Status updates once approved by a clinician. Recommendations flagged as high-risk or generated with low data confidence are automatically escalated for priority clinical review.</p>
          <p class="status-badge" [ngClass]="statusBadgeClass(insights.recommendations)">
            {{ overallReviewStatusLabel(insights.recommendations) }}
          </p>
          <p><strong>Score:</strong> {{ insights.overallScore }} | <strong>Confidence:</strong> {{ toPercent(insights.confidence) }}</p>
          <ul>
            <li class="recommendation-item" *ngFor="let rec of insights.recommendations">
              <strong>{{ rec.title }}</strong>
              <p *ngIf="rec.isClinicianApproved" class="approved-badge">
                Clinician approved{{ rec.approvedAtUtc ? (' at ' + (rec.approvedAtUtc | date:'medium')) : '' }}
              </p>
              <p><strong>Status:</strong> {{ recommendationStatusLabel(rec) }}<span *ngIf="rec.approvedAtUtc"> ({{ rec.approvedAtUtc | date:'short' }})</span></p>
              <p>{{ rec.content }}</p>
              <button
                mat-stroked-button
                color="primary"
                class="request-review-btn"
                *ngIf="canRequestReview(rec)"
                (click)="requestReview(rec.id)"
                [disabled]="requestingReviewIds().has(rec.id)">
                {{ requestingReviewIds().has(rec.id) ? 'Requesting...' : 'Request clinician review' }}
              </button>
            </li>
          </ul>
        </ng-container>
      </div>

      <div *ngIf="selectedDocId() === doc.documentId && activePanel() === 'biomarkers' && selectedBiomarkers().length" class="insight-block">
        <p class="table-title"><strong>Biomarker Readings</strong></p>
        <table class="data-table">
          <thead>
            <tr>
              <th>Biomarker</th>
              <th>Value</th>
              <th>Unit</th>
              <th>Source</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let b of selectedBiomarkers()">
              <td class="code-cell">{{ b.biomarkerCode }}</td>
              <td>{{ b.value }}</td>
              <td>{{ b.unit }}</td>
              <td><span class="source-badge" [class.source-manual]="b.sourceType === 2">{{ sourceTypeLabel(b.sourceType) }}</span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div *ngIf="selectedDocId() === doc.documentId && activePanel() === 'jobs' && selectedJobs().length" class="insight-block">
        <p class="table-title"><strong>Job History</strong></p>
        <table class="data-table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Type</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let j of selectedJobs()">
              <td>{{ j.createdAtUtc | date:'short' }}</td>
              <td>{{ jobTypeLabel(j.type) }}</td>
              <td><span class="job-status-badge" [ngClass]="jobStatusClass(j.status)">{{ jobStatusLabel(j.status) }}</span></td>
            </tr>
          </tbody>
        </table>
      </div>
    </mat-card>

    <mat-card>
      <h3>Recent Insight Snapshots</h3>
      <ul>
        <li *ngFor="let item of insightHistory()">
          {{ item.createdAtUtc | date:'short' }} - score {{ item.overallScore }} (doc {{ item.documentId }})
          <span class="status-badge" [ngClass]="snapshotBadgeClass(item)">
            {{ snapshotStatusLabel(item) }}
          </span>
        </li>
      </ul>
    </mat-card>
  `,
  styles: [
    `
      .history-item { margin-top: 12px; padding: 16px 20px 20px; box-sizing: border-box; }
      mat-card { padding: 16px 20px 20px; box-sizing: border-box; }
      .doc-actions { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 4px; margin-bottom: 4px; }
      .insight-block { margin-top: 12px; padding: 14px 16px 16px; background: #f5f7ff; border-radius: 8px; }
      .table-title { margin: 0 0 10px; }
      .data-table { width: 100%; border-collapse: collapse; font-size: 0.88rem; }
      .data-table th { text-align: left; padding: 7px 12px; background: rgba(63,81,181,0.09); color: #1a237e; font-weight: 600; border-bottom: 2px solid rgba(63,81,181,0.18); }
      .data-table td { padding: 7px 12px; border-bottom: 1px solid rgba(0,0,0,0.07); vertical-align: middle; }
      .data-table tbody tr:last-child td { border-bottom: none; }
      .data-table tbody tr:hover td { background: rgba(63,81,181,0.04); }
      .code-cell { font-family: monospace; font-size: 0.82rem; color: #37474f; word-break: break-all; }
      .source-badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 0.78rem; font-weight: 600; background: rgba(25,118,210,0.12); color: #0d47a1; }
      .source-manual { background: rgba(123,31,162,0.12); color: #4a148c; }
      .job-status-badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 0.78rem; font-weight: 600; }
      .job-succeeded { background: rgba(46,125,50,0.13); color: #1b5e20; }
      .job-failed { background: rgba(211,47,47,0.12); color: #b71c1c; }
      .job-insufficient { background: rgba(237,108,2,0.13); color: #8a4b00; }
      .job-processing { background: rgba(25,118,210,0.12); color: #0d47a1; }
      .job-default { background: rgba(0,0,0,0.07); color: #424242; }
      button { margin-right: 8px; }
      .recommendation-item { margin-bottom: 22px; padding-bottom: 14px; border-bottom: 1px solid rgba(0,0,0,0.12); }
      .generating-overlay { display: flex; align-items: center; gap: 12px; padding: 8px 0 14px; }
      @keyframes spin { to { transform: rotate(360deg); } }
      .btn-spinner-wrap { display: inline-flex; align-items: center; gap: 6px; }
      .btn-spinner { display: inline-block; width: 13px; height: 13px; border: 2px solid currentColor; border-top-color: transparent; border-radius: 50%; animation: spin 0.7s linear infinite; }
      .lg-spinner { display: inline-block; width: 26px; height: 26px; border: 3px solid #3f51b5; border-top-color: transparent; border-radius: 50%; animation: spin 0.8s linear infinite; flex-shrink: 0; }
      .generating-text { margin: 0; color: #3f51b5; font-weight: 500; }
      .request-review-btn { margin-top: 8px; margin-bottom: 6px; }
      .approved-badge {
        display: inline-block;
        padding: 4px 8px;
        border-radius: 999px;
        background: rgba(46, 125, 50, 0.14);
        color: #1b5e20;
        font-weight: 600;
      }
      .status-badge {
        display: inline-block;
        padding: 4px 10px;
        border-radius: 999px;
        font-weight: 600;
      }
      .status-approved {
        background: rgba(46, 125, 50, 0.14);
        color: #1b5e20;
      }
      .status-review-requested {
        background: rgba(237, 108, 2, 0.14);
        color: #8a4b00;
      }
      .status-pending {
        background: rgba(25, 118, 210, 0.14);
        color: #0d47a1;
      }
    `,
  ],
})
export class HistoryComponent {
  protected readonly documents = signal<DocumentHistoryItem[]>([]);
  protected readonly selectedBiomarkers = signal<BiomarkerHistoryItem[]>([]);
  protected readonly selectedJobs = signal<JobHistoryItem[]>([]);
  protected readonly insightHistory = signal<InsightHistoryItem[]>([]);
  protected readonly selectedInsights = signal<InsightSnapshotResponse | null>(null);
  protected readonly selectedDocId = signal<string | null>(null);
  protected readonly activePanel = signal<'insights' | 'biomarkers' | 'jobs' | null>(null);
  protected readonly generatingInsightsDocId = signal<string | null>(null);
  protected readonly requestingReviewIds = signal<Set<string>>(new Set<string>());

  constructor(private readonly api: ApiService) {
    this.reload();
  }

  reload(): void {
    this.api.getHistoryDocuments().subscribe({
      next: (docs) => this.documents.set(docs),
      error: () => this.documents.set([]),
    });

    this.api.getInsightHistory().subscribe({
      next: (rows) => this.insightHistory.set(rows),
      error: () => this.insightHistory.set([]),
    });
  }

  loadDocumentInsights(docId: string): void {
    this.selectedDocId.set(docId);
    this.activePanel.set('insights');
    this.selectedBiomarkers.set([]);
    this.selectedJobs.set([]);
    this.api.getDocumentInsights(docId).subscribe({
      next: (res) => this.selectedInsights.set(res),
      error: () => this.selectedInsights.set(null),
    });
  }

  generateDocumentInsights(docId: string): void {
    this.selectedDocId.set(docId);
    this.activePanel.set('insights');
    this.selectedInsights.set(null);
    this.selectedBiomarkers.set([]);
    this.selectedJobs.set([]);
    this.generatingInsightsDocId.set(docId);
    this.api.generateDocumentInsights(docId).subscribe({
      next: (res) => {
        this.selectedInsights.set(res);
        this.generatingInsightsDocId.set(null);
      },
      error: () => {
        this.selectedInsights.set(null);
        this.generatingInsightsDocId.set(null);
      },
    });
  }

  loadDocBiomarkers(docId: string): void {
    this.selectedDocId.set(docId);
    this.activePanel.set('biomarkers');
    this.selectedInsights.set(null);
    this.selectedJobs.set([]);
    this.api.getDocumentBiomarkers(docId).subscribe({
      next: (rows) => this.selectedBiomarkers.set(rows),
      error: () => this.selectedBiomarkers.set([]),
    });
  }

  loadDocJobs(docId: string): void {
    this.selectedDocId.set(docId);
    this.activePanel.set('jobs');
    this.selectedInsights.set(null);
    this.selectedBiomarkers.set([]);
    this.api.getDocumentJobs(docId).subscribe({
      next: (rows) => this.selectedJobs.set(rows),
      error: () => this.selectedJobs.set([]),
    });
  }

  toPercent(confidence: number): string {
    return `${Math.round(confidence * 100)}%`;
  }

  documentStatusLabel(status: number): string {
    switch (status) {
      case 1:
        return 'Uploaded';
      case 2:
        return 'Processing';
      case 3:
        return 'Processed';
      case 4:
        return 'Failed';
      default:
        return `Unknown (${status})`;
    }
  }

  jobStatusLabel(status: number): string {
    switch (status) {
      case 1:
        return 'Ready';
      case 2:
        return 'Processing';
      case 3:
        return 'Succeeded';
      case 4:
        return 'Failed';
      case 5:
        return 'Insufficient Data';
      default:
        return `Unknown (${status})`;
    }
  }

  jobTypeLabel(type: number): string {
    switch (type) {
      case 1:
        return 'OCR Lab PDF';
      case 2:
        return 'Parse VCF';
      case 3:
        return 'Normalize';
      case 4:
        return 'Score Recalculation';
      case 5:
        return 'Generate Recommendations';
      default:
        return `Unknown (${type})`;
    }
  }

  jobStatusClass(status: number): string {
    switch (status) {
      case 3: return 'job-status-badge job-succeeded';
      case 4: return 'job-status-badge job-failed';
      case 5: return 'job-status-badge job-insufficient';
      case 2: return 'job-status-badge job-processing';
      default: return 'job-status-badge job-default';
    }
  }

  sourceTypeLabel(sourceType: number): string {
    switch (sourceType) {
      case 1:
        return 'OCR';
      case 2:
        return 'Manual';
      default:
        return `Unknown (${sourceType})`;
    }
  }

  recommendationStatusLabel(recommendation: InsightRecommendation): string {
    if (recommendation.isClinicianApproved || recommendation.status === 3) {
      return 'Clinician approved';
    }

    if (recommendation.status === 2) {
      return 'Review requested';
    }

    return 'AI generated - pending clinician validation';
  }

  canRequestReview(recommendation: InsightRecommendation): boolean {
    if (recommendation.isClinicianApproved || recommendation.status === 3) {
      return false;
    }

    return recommendation.status !== 2;
  }

  overallReviewStatusLabel(recommendations: InsightRecommendation[]): string {
    if (recommendations.length === 0) {
      return 'No recommendations';
    }

    const approvedCount = recommendations.filter((r) => r.isClinicianApproved || r.status === 3).length;
    const requestedCount = recommendations.filter((r) => r.status === 2 && !r.isClinicianApproved).length;

    if (approvedCount === recommendations.length) {
      return 'Recommendation clinician approved';
    }

    if (requestedCount > 0 || approvedCount > 0) {
      return `${approvedCount}/${recommendations.length} clinician approved`;
    }

    return 'Pending clinician validation';
  }

  statusBadgeClass(recommendations: InsightRecommendation[]): string {
    if (recommendations.length === 0) return 'status-pending';

    const approvedCount = recommendations.filter((r) => r.isClinicianApproved || r.status === 3).length;
    const requestedCount = recommendations.filter((r) => r.status === 2 && !r.isClinicianApproved).length;

    if (approvedCount === recommendations.length) return 'status-approved';
    if (requestedCount > 0 || approvedCount > 0) return 'status-review-requested';
    return 'status-pending';
  }

  snapshotStatusLabel(item: InsightHistoryItem): string {
    const total = item.recommendationCount ?? 0;
    const approved = item.approvedRecommendationCount ?? 0;
    const reviewRequested = item.reviewRequestedRecommendationCount ?? 0;

    if (total === 0) return 'No recommendations';
    if (approved === total) return 'All recommendations clinician approved';
    if (reviewRequested > 0 || approved > 0) return `${approved}/${total} clinician approved`;
    return 'Pending clinician validation';
  }

  snapshotBadgeClass(item: InsightHistoryItem): string {
    const total = item.recommendationCount ?? 0;
    const approved = item.approvedRecommendationCount ?? 0;
    const reviewRequested = item.reviewRequestedRecommendationCount ?? 0;

    if (total === 0) return 'status-pending';
    if (approved === total) return 'status-approved';
    if (reviewRequested > 0 || approved > 0) return 'status-review-requested';
    return 'status-pending';
  }

  requestReview(recommendationId: string): void {
    this.requestingReviewIds.update((current) => {
      const next = new Set(current);
      next.add(recommendationId);
      return next;
    });

    this.api.requestRecommendationReview(recommendationId).subscribe({
      next: (updatedRecommendation) => {
        this.selectedInsights.update((currentInsights) => {
          if (!currentInsights) return currentInsights;

          return {
            ...currentInsights,
            recommendations: currentInsights.recommendations.map((recommendation) =>
              recommendation.id === updatedRecommendation.id ? updatedRecommendation : recommendation,
            ),
          };
        });

        this.requestingReviewIds.update((current) => {
          const next = new Set(current);
          next.delete(recommendationId);
          return next;
        });
      },
      error: () => {
        this.requestingReviewIds.update((current) => {
          const next = new Set(current);
          next.delete(recommendationId);
          return next;
        });
      },
    });
  }
}
