import { Component, signal } from '@angular/core';
import { DatePipe, NgClass, NgFor, NgIf } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';
import {
  BiomarkerHistoryItem,
  DocumentHistoryItem,
  InsightRecommendation,
  InsightHistoryItem,
  InsightSnapshotResponse,
  JobHistoryItem,
} from '../../core/models/api.models';

@Component({
  selector: 'app-history',
  standalone: true,
  imports: [NgFor, NgIf, NgClass, DatePipe, MatCardModule, MatButtonModule],
  template: `
    <mat-card>
      <h2>My Uploaded Documents</h2>
      <p>Server-driven history of your uploads and biomarker records.</p>
      <button mat-button (click)="reload()">Refresh</button>
    </mat-card>

    <mat-card *ngFor="let doc of documents()" class="history-item">
      <h3>{{ doc.fileName || 'Unnamed file' }}</h3>
      <p>Document ID: {{ doc.documentId }}</p>
      <p>Uploaded at: {{ doc.createdAtUtc | date:'medium' }}</p>
      <p>Doc status: {{ documentStatusLabel(doc.documentStatus) }}, Job status: {{ doc.latestJobStatus ? jobStatusLabel(doc.latestJobStatus) : '-' }}</p>
      <p>Biomarkers: {{ doc.biomarkerCount }} (manual: {{ doc.manualBiomarkerCount }})</p>
      <p *ngIf="doc.missingMandatoryBiomarkers?.length">Missing mandatory: {{ doc.missingMandatoryBiomarkers?.join(', ') }}</p>
      <button mat-stroked-button (click)="loadDocumentInsights(doc.documentId)">Load Doc Insights</button>
      <button mat-stroked-button (click)="generateDocumentInsights(doc.documentId)">Generate Doc Insights</button>
      <button mat-stroked-button (click)="loadDocBiomarkers(doc.documentId)">Show Biomarkers</button>
      <button mat-stroked-button (click)="loadDocJobs(doc.documentId)">Show Jobs</button>

      <div *ngIf="selectedDocId() === doc.documentId && selectedInsights() as insights" class="insight-block">
        <p><strong>Note:</strong> Recommendations are generated by AI and should be clinically validated. Status updates once approved by a clinician.</p>
        <p class="status-badge" [ngClass]="statusBadgeClass(insights.recommendations)">
          {{ overallReviewStatusLabel(insights.recommendations) }}
        </p>
        <p><strong>Score:</strong> {{ insights.overallScore }} | <strong>Confidence:</strong> {{ toPercent(insights.confidence) }}</p>
        <ul>
          <li *ngFor="let rec of insights.recommendations">
            <strong>{{ rec.title }}</strong>
            <p *ngIf="rec.isClinicianApproved" class="approved-badge">
              Clinician approved{{ rec.approvedAtUtc ? (' at ' + (rec.approvedAtUtc | date:'medium')) : '' }}
            </p>
            <p><strong>Status:</strong> {{ recommendationStatusLabel(rec) }}<span *ngIf="rec.approvedAtUtc"> ({{ rec.approvedAtUtc | date:'short' }})</span></p>
            <p>{{ rec.content }}</p>
            <button
              mat-stroked-button
              color="primary"
              *ngIf="canRequestReview(rec)"
              (click)="requestReview(rec.id)"
              [disabled]="requestingReviewIds().has(rec.id)">
              {{ requestingReviewIds().has(rec.id) ? 'Requesting...' : 'Request clinician review' }}
            </button>
          </li>
        </ul>
      </div>

      <div *ngIf="selectedDocId() === doc.documentId && selectedBiomarkers().length" class="insight-block">
        <p><strong>Biomarker rows:</strong></p>
        <ul>
          <li *ngFor="let b of selectedBiomarkers()">
            {{ b.biomarkerCode }}: {{ b.value }} {{ b.unit }} (source {{ sourceTypeLabel(b.sourceType) }})
          </li>
        </ul>
      </div>

      <div *ngIf="selectedDocId() === doc.documentId && selectedJobs().length" class="insight-block">
        <p><strong>Job history:</strong></p>
        <ul>
          <li *ngFor="let j of selectedJobs()">
            {{ j.createdAtUtc | date:'short' }} - type {{ jobTypeLabel(j.type) }} status {{ jobStatusLabel(j.status) }}
          </li>
        </ul>
      </div>
    </mat-card>

    <mat-card>
      <h3>Recent Insight Snapshots</h3>
      <ul>
        <li *ngFor="let item of insightHistory()">
          {{ item.createdAtUtc | date:'short' }} - score {{ item.overallScore }} (doc {{ item.documentId }})
          <span class="status-badge" [ngClass]="snapshotBadgeClass(item)">
            {{ snapshotStatusLabel(item) }}
          </span>
        </li>
      </ul>
    </mat-card>
  `,
  styles: [
    `
      .history-item { margin-top: 12px; }
      .insight-block { margin-top: 10px; padding: 10px; background: #f5f7ff; border-radius: 8px; }
      button { margin-right: 8px; }
      .approved-badge {
        display: inline-block;
        padding: 4px 8px;
        border-radius: 999px;
        background: rgba(46, 125, 50, 0.14);
        color: #1b5e20;
        font-weight: 600;
      }
      .status-badge {
        display: inline-block;
        padding: 4px 10px;
        border-radius: 999px;
        font-weight: 600;
      }
      .status-approved {
        background: rgba(46, 125, 50, 0.14);
        color: #1b5e20;
      }
      .status-review-requested {
        background: rgba(237, 108, 2, 0.14);
        color: #8a4b00;
      }
      .status-pending {
        background: rgba(25, 118, 210, 0.14);
        color: #0d47a1;
      }
    `,
  ],
})
export class HistoryComponent {
  protected readonly documents = signal<DocumentHistoryItem[]>([]);
  protected readonly selectedBiomarkers = signal<BiomarkerHistoryItem[]>([]);
  protected readonly selectedJobs = signal<JobHistoryItem[]>([]);
  protected readonly insightHistory = signal<InsightHistoryItem[]>([]);
  protected readonly selectedInsights = signal<InsightSnapshotResponse | null>(null);
  protected readonly selectedDocId = signal<string | null>(null);
  protected readonly requestingReviewIds = signal<Set<string>>(new Set<string>());

  constructor(private readonly api: ApiService) {
    this.reload();
  }

  reload(): void {
    this.api.getHistoryDocuments().subscribe({
      next: (docs) => this.documents.set(docs),
      error: () => this.documents.set([]),
    });

    this.api.getInsightHistory().subscribe({
      next: (rows) => this.insightHistory.set(rows),
      error: () => this.insightHistory.set([]),
    });
  }

  loadDocumentInsights(docId: string): void {
    this.selectedDocId.set(docId);
    this.api.getDocumentInsights(docId).subscribe({
      next: (res) => this.selectedInsights.set(res),
      error: () => this.selectedInsights.set(null),
    });
  }

  generateDocumentInsights(docId: string): void {
    this.selectedDocId.set(docId);
    this.api.generateDocumentInsights(docId).subscribe({
      next: (res) => this.selectedInsights.set(res),
      error: () => this.selectedInsights.set(null),
    });
  }

  loadDocBiomarkers(docId: string): void {
    this.selectedDocId.set(docId);
    this.api.getDocumentBiomarkers(docId).subscribe({
      next: (rows) => this.selectedBiomarkers.set(rows),
      error: () => this.selectedBiomarkers.set([]),
    });
  }

  loadDocJobs(docId: string): void {
    this.selectedDocId.set(docId);
    this.api.getDocumentJobs(docId).subscribe({
      next: (rows) => this.selectedJobs.set(rows),
      error: () => this.selectedJobs.set([]),
    });
  }

  toPercent(confidence: number): string {
    return `${Math.round(confidence * 100)}%`;
  }

  documentStatusLabel(status: number): string {
    switch (status) {
      case 1:
        return 'Uploaded';
      case 2:
        return 'Processing';
      case 3:
        return 'Processed';
      case 4:
        return 'Failed';
      default:
        return `Unknown (${status})`;
    }
  }

  jobStatusLabel(status: number): string {
    switch (status) {
      case 1:
        return 'Ready';
      case 2:
        return 'Processing';
      case 3:
        return 'Succeeded';
      case 4:
        return 'Failed';
      case 5:
        return 'Insufficient Data';
      default:
        return `Unknown (${status})`;
    }
  }

  jobTypeLabel(type: number): string {
    switch (type) {
      case 1:
        return 'OCR Lab PDF';
      case 2:
        return 'Parse VCF';
      case 3:
        return 'Normalize';
      case 4:
        return 'Score Recalculation';
      case 5:
        return 'Generate Recommendations';
      default:
        return `Unknown (${type})`;
    }
  }

  sourceTypeLabel(sourceType: number): string {
    switch (sourceType) {
      case 1:
        return 'OCR';
      case 2:
        return 'Manual';
      default:
        return `Unknown (${sourceType})`;
    }
  }

  recommendationStatusLabel(recommendation: InsightRecommendation): string {
    if (recommendation.isClinicianApproved || recommendation.status === 3) {
      return 'Clinician approved';
    }

    if (recommendation.status === 2) {
      return 'Review requested';
    }

    return 'AI generated - pending clinician validation';
  }

  canRequestReview(recommendation: InsightRecommendation): boolean {
    if (recommendation.isClinicianApproved || recommendation.status === 3) {
      return false;
    }

    return recommendation.status !== 2;
  }

  overallReviewStatusLabel(recommendations: InsightRecommendation[]): string {
    if (recommendations.length === 0) {
      return 'No recommendations';
    }

    const approvedCount = recommendations.filter((r) => r.isClinicianApproved || r.status === 3).length;
    const requestedCount = recommendations.filter((r) => r.status === 2 && !r.isClinicianApproved).length;

    if (approvedCount === recommendations.length) {
      return 'Recommendation clinician approved';
    }

    if (requestedCount > 0 || approvedCount > 0) {
      return `${approvedCount}/${recommendations.length} clinician approved`;
    }

    return 'Pending clinician validation';
  }

  statusBadgeClass(recommendations: InsightRecommendation[]): string {
    if (recommendations.length === 0) return 'status-pending';

    const approvedCount = recommendations.filter((r) => r.isClinicianApproved || r.status === 3).length;
    const requestedCount = recommendations.filter((r) => r.status === 2 && !r.isClinicianApproved).length;

    if (approvedCount === recommendations.length) return 'status-approved';
    if (requestedCount > 0 || approvedCount > 0) return 'status-review-requested';
    return 'status-pending';
  }

  snapshotStatusLabel(item: InsightHistoryItem): string {
    const total = item.recommendationCount ?? 0;
    const approved = item.approvedRecommendationCount ?? 0;
    const reviewRequested = item.reviewRequestedRecommendationCount ?? 0;

    if (total === 0) return 'No recommendations';
    if (approved === total) return 'All recommendations clinician approved';
    if (reviewRequested > 0 || approved > 0) return `${approved}/${total} clinician approved`;
    return 'Pending clinician validation';
  }

  snapshotBadgeClass(item: InsightHistoryItem): string {
    const total = item.recommendationCount ?? 0;
    const approved = item.approvedRecommendationCount ?? 0;
    const reviewRequested = item.reviewRequestedRecommendationCount ?? 0;

    if (total === 0) return 'status-pending';
    if (approved === total) return 'status-approved';
    if (reviewRequested > 0 || approved > 0) return 'status-review-requested';
    return 'status-pending';
  }

  requestReview(recommendationId: string): void {
    this.requestingReviewIds.update((current) => {
      const next = new Set(current);
      next.add(recommendationId);
      return next;
    });

    this.api.requestRecommendationReview(recommendationId).subscribe({
      next: (updatedRecommendation) => {
        this.selectedInsights.update((currentInsights) => {
          if (!currentInsights) return currentInsights;

          return {
            ...currentInsights,
            recommendations: currentInsights.recommendations.map((recommendation) =>
              recommendation.id === updatedRecommendation.id ? updatedRecommendation : recommendation,
            ),
          };
        });

        this.requestingReviewIds.update((current) => {
          const next = new Set(current);
          next.delete(recommendationId);
          return next;
        });
      },
      error: () => {
        this.requestingReviewIds.update((current) => {
          const next = new Set(current);
          next.delete(recommendationId);
          return next;
        });
      },
    });
  }
}
