import { Component, signal } from '@angular/core';
import { DatePipe, NgClass, NgFor, NgIf } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { ApiService } from '../../core/services/api.service';
import { InsightRecommendation, InsightSnapshotResponse } from '../../core/models/api.models';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [NgFor, NgIf, NgClass, DatePipe, MatCardModule, MatButtonModule],
  template: `
    <div class="dashboard-grid">
      <mat-card class="dashboard-card">
        <h2>Health Insights (Aggregate)</h2>
        <p>Based on latest biomarker values across your documents.</p>
        <p><strong>Note:</strong> Recommendations are generated by AI and should be clinically validated. Status will update once reviewed and approved by a clinician. Recommendations flagged as high-risk or generated with low data confidence are automatically escalated for priority clinical review.</p>
        <button mat-flat-button color="primary" class="primary-action" (click)="generateInsights()" [disabled]="loading()">
          {{ loading() ? 'Generating...' : 'Generate / Refresh Insights' }}
        </button>
        <p class="error" *ngIf="error()">{{ error() }}</p>
      </mat-card>

      <mat-card class="dashboard-card" *ngIf="insights() as data">
        <h3>Score: {{ data.overallScore }}</h3>
         <p class="status-badge" [ngClass]="statusBadgeClass(data.recommendations)">
           {{ overallReviewStatusLabel(data.recommendations) }}
         </p>
        <p>Confidence: {{ toPercent(data.confidence) }}</p>
        <p>Risk band: {{ riskBandLabel(data.riskBand) }}</p>
        <p>Scope: {{ data.scope }}</p>
        <p>Contributing docs: {{ data.contributingDocumentIds.length }}</p>
      </mat-card>

      <mat-card class="dashboard-card" *ngIf="insights() as data">
        <h3>Recommendations</h3>
        <div *ngIf="data.recommendations.length === 0">No recommendations available yet.</div>
        <ul>
          <li class="recommendation-item" *ngFor="let r of data.recommendations">
            <strong>{{ r.title }}</strong>
            <p *ngIf="r.isClinicianApproved" class="approved-badge">
              Clinician approved{{ r.approvedAtUtc ? (' at ' + (r.approvedAtUtc | date:'medium')) : '' }}
            </p>
            <p><strong>Status:</strong> {{ recommendationStatusLabel(r) }}<span *ngIf="r.approvedAtUtc"> ({{ r.approvedAtUtc | date:'short' }})</span></p>
            <p>{{ r.content }}</p>
            <button
              mat-stroked-button
              color="primary"
              class="request-review-btn"
              *ngIf="canRequestReview(r)"
              (click)="requestReview(r.id)"
              [disabled]="requestingReviewIds().has(r.id)">
              {{ requestingReviewIds().has(r.id) ? 'Requesting...' : 'Request clinician review' }}
            </button>
          </li>
        </ul>
      </mat-card>
    </div>
  `,
  styles: [
    `
      .dashboard-grid { display: grid; gap: 16px; }
      .dashboard-card { padding: 16px 18px 18px; box-sizing: border-box; }
      .primary-action { margin-top: 10px; }
      .error { color: #b00020; margin-top: 8px; }
      ul { padding-left: 20px; margin: 10px 0 0; }
      .recommendation-item { margin-bottom: 22px; padding-bottom: 14px; border-bottom: 1px solid rgba(0,0,0,0.08); }
      .recommendation-item:last-child { margin-bottom: 0; padding-bottom: 0; border-bottom: none; }
      .request-review-btn { margin-top: 8px; margin-bottom: 6px; }
      li { margin-bottom: 12px; }
      p { margin: 6px 0; }
      .approved-badge {
        display: inline-block;
        padding: 4px 8px;
        border-radius: 999px;
        background: rgba(46, 125, 50, 0.14);
        color: #1b5e20;
        font-weight: 600;
      }
       .status-badge {
         display: inline-block;
         padding: 4px 10px;
         border-radius: 999px;
         font-weight: 600;
       }
       .status-approved {
         background: rgba(46, 125, 50, 0.14);
         color: #1b5e20;
       }
       .status-review-requested {
         background: rgba(237, 108, 2, 0.14);
         color: #8a4b00;
       }
       .status-pending {
         background: rgba(25, 118, 210, 0.14);
         color: #0d47a1;
       }
    `,
  ],
})
export class DashboardComponent {
  protected readonly insights = signal<InsightSnapshotResponse | null>(null);
  protected readonly loading = signal(false);
  protected readonly error = signal('');
  protected readonly requestingReviewIds = signal<Set<string>>(new Set<string>());

  constructor(private readonly api: ApiService) {
    this.loadLatest();
  }

  loadLatest(): void {
    this.api.getAggregateInsights().subscribe({
      next: (res) => this.insights.set(res),
      error: () => this.insights.set(null),
    });
  }

  generateInsights(): void {
    this.loading.set(true);
    this.error.set('');
    this.api.generateAggregateInsights().subscribe({
      next: (res) => {
        this.insights.set(res);
        this.loading.set(false);
      },
      error: (e) => {
        this.loading.set(false);
        this.error.set(e?.error?.message ?? 'Unable to generate insights.');
      },
    });
  }

  toPercent(confidence: number): string {
    return `${Math.round(confidence * 100)}%`;
  }

  riskBandLabel(band: number): string {
    if (band === 1) return 'Low';
    if (band === 2) return 'Moderate';
    return 'High';
  }

  overallReviewStatusLabel(recommendations: InsightRecommendation[]): string {
    if (recommendations.length === 0) {
      return 'No recommendations';
    }

    const approvedCount = recommendations.filter((r) => r.isClinicianApproved || r.status === 3).length;
    const requestedCount = recommendations.filter((r) => r.status === 2 && !r.isClinicianApproved).length;

    if (approvedCount === recommendations.length) {
      return 'All recommendations clinician approved';
    }

    if (requestedCount > 0 || approvedCount > 0) {
      return `${approvedCount}/${recommendations.length} clinician approved`; 
    }

    return 'Pending clinician validation';
  }

  statusBadgeClass(recommendations: InsightRecommendation[]): string {
    if (recommendations.length === 0) return 'status-pending';

    const approvedCount = recommendations.filter((r) => r.isClinicianApproved || r.status === 3).length;
    const requestedCount = recommendations.filter((r) => r.status === 2 && !r.isClinicianApproved).length;

    if (approvedCount === recommendations.length) return 'status-approved';
    if (requestedCount > 0 || approvedCount > 0) return 'status-review-requested';
    return 'status-pending';
  }

  recommendationStatusLabel(recommendation: InsightRecommendation): string {
    if (recommendation.isClinicianApproved || recommendation.status === 3) {
      return 'Clinician approved';
    }

    if (recommendation.status === 2) {
      return 'Review requested';
    }

    return 'AI generated - pending clinician validation';
  }

  canRequestReview(recommendation: InsightRecommendation): boolean {
    if (recommendation.isClinicianApproved || recommendation.status === 3) {
      return false;
    }

    return recommendation.status !== 2;
  }

  requestReview(recommendationId: string): void {
    this.requestingReviewIds.update((current) => {
      const next = new Set(current);
      next.add(recommendationId);
      return next;
    });

    this.api.requestRecommendationReview(recommendationId).subscribe({
      next: (updatedRecommendation) => {
        this.insights.update((currentInsights) => {
          if (!currentInsights) return currentInsights;

          return {
            ...currentInsights,
            recommendations: currentInsights.recommendations.map((recommendation) =>
              recommendation.id === updatedRecommendation.id ? updatedRecommendation : recommendation,
            ),
          };
        });

        this.requestingReviewIds.update((current) => {
          const next = new Set(current);
          next.delete(recommendationId);
          return next;
        });
      },
      error: (e) => {
        this.error.set(e?.error?.message ?? 'Unable to request clinician review.');
        this.requestingReviewIds.update((current) => {
          const next = new Set(current);
          next.delete(recommendationId);
          return next;
        });
      },
    });
  }
}
